// ServiceControlCOM.idl: источник языка IDL для ServiceControlCOM
//

// Этот файл будет обработан средством MIDL для
// создание библиотеки типов ($handlersafeidlname$.tlb) и кода маршалирования.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(4557e734-2814-4b45-bfb7-d074c5219b78),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IServiceManager : IDispatch
{	
	[id(1)] HRESULT startSvc();
	[propget, id(2)] HRESULT ServiceName([out, retval] BSTR* pVal);
	[propput, id(2)] HRESULT ServiceName([in] BSTR newVal);
	[propget, id(3)] HRESULT LastError([out, retval] INT* pVal);
	[propget, id(4)] HRESULT CurrentState([out, retval] INT* pVal);
	[propget, id(5)] HRESULT ExitCode([out, retval] INT* pVal);
	[propget, id(6)] HRESULT CheckPoint([out, retval] INT* pVal);
	[propget, id(7)] HRESULT WaitHint([out, retval] INT* pVal);
	
	[id(8)] HRESULT stopSvc();
	[id(9)] HRESULT chkStatus([out] BYTE* status);
	[propget, id(10)] HRESULT AllSvcNames([out, retval] BSTR* pVal);
	
	[id(11)] HRESULT clearMem();
};
[
	uuid(520defd6-ad15-429b-8a77-32491b91655b),
	version(1.0),
]
library ServiceControlCOMLib
{
	importlib("stdole2.tlb");
	[
		uuid(b0c6ba7c-e601-4dc9-971e-8d4319fcd912)
	]
	coclass ServiceManager
	{
		[default] interface IServiceManager;
	};
};

import "shobjidl.idl";
